// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnsrksjsbeoivpozknot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuc3Jrc2pzYmVvaXZwb3prbm90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MzU4NjYsImV4cCI6MjA2NjQxMTg2Nn0.KNYbkl54YqikOxBdGKNOOEwY4t9BAOrms_L31ceH7tY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);